# Site

title: Manipulating Tabular Data
baseurl: /data-manipulation-in-R-lesson
email: cyberhelp@sesync.org
description: ""
styleurl: https://cdn.rawgit.com/sesync-ci/lesson-stylesheets/1.0.1
# styleurl: https://rawgit.com/sesync-ci/lesson-stylesheets/master
reveal: https://cdn.rawgit.com/hakimel/reveal.js/3.3.0
lesson: 4

# Slides

slide_sorter:
  - title
  - intro
  - tidy
  - gather
  - data
  - dplyr
  - pipe
  - conclude
  - solutions

# Jekyll

markdown: kramdown
kramdown:
  toc_levels: 2..2
collections:
  - slides
exclude:
  - README.md
  - build.R
  - "*.Rproj"
  - "*.Rmd"
