baseurl: /data-manipulation-in-R-lesson
styleurl: https://cdn.rawgit.com/SESYNC-ci/lesson-stylesheets

kramdown:
  parse_block_html: true
  toc_levels: 2..2
exclude:
  - '*.Rmd'
defaults:
  -
    scope:
      path: ''
    values:
      layout: 'default'
